const studentscsa = [
    { rollNo: 1, name: "AANAND KRISHNAN", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 2, name: "AASHIN MOHAMMED A Z", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 3, name: "AAVANI AALOLA", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 4, name: "ABHINAV A", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 5, name: "ABHINAV PV", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 6, name: "ADITHYAN S", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 7, name: "AISWARYA S", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 8, name: "AKASH KUMAR SINGH", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 9, name: "AKSHAY VS", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 10, name: "ALAN SHOBY", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 11, name: "ALEX RUSSEL", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 12, name: "ALINA THOMAS", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 13, name: "AMAN RAJ", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 14, name: "AMAN SAMI PONNATH SIDDIQUE", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 15, name: "AMI ASOK", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 16, name: "AMRITHA SANTHOSH", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 17, name: "ANAGHA A", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 18, name: "ANAGHA P", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 19, name: "ANAGHA P S", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 20, name: "ANANDARAJ M", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 21, name: "ANANTH K", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 22, name: "ANILA ROY", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 23, name: "ANJANA KRISHNA V", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 24, name: "ANNRIN SHAJU", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 25, name: "ANUKRISHNA T K", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 26, name: "ANUPAMA A R", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 27, name: "ARJUN BIJUMON", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 28, name: "ARJUN J KRISHNA", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 29, name: "A S ABHISHEK", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 30, name: "ASWATHI K", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 31, name: "ASWATHY G PANICKER", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 32, name: "BHAGATH BIJU", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 33, name: "BHARTI KUMARI", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 34, name: "CHRIS GEORGE MANOJ", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 35, name: "DEEPANSHU KUMAR", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 36, name: "DEVANANDANA K P", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 37, name: "EMILIA ANNA ANTONY", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 38, name: "GLISTY SAJAN", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 39, name: "GOKUL RAJEEV", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 40, name: "GOURI LAKSHMI M S", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 41, name: "GOUTHAM KRISHNA", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 42, name: "HARIKRISHNAN K R", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 43, name: "HARISANKAR K", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 44, name: "HARISHANKAR C", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 45, name: "KARTHIK S S", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 46, name: "ABHINAV V", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 47, name: "AKHIL V U", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" },
    { rollNo: 48, name: "AKSA SALAS", status: "Absent", time: "N/A", date: "N/A", sub: "N/A" }
];

export default studentscsa